modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "recraftcollect"
version = "${file.jarVersion}"
displayName = "ReCraft Collect - Zombie Purge"
description = '''
Comptabilise les kills de zombies en points par categorie (server-side only).
Tuez des zombies pour atteindre l'objectif communautaire : Purger le monde - 1 000 000 points !
'''
authors = "Vyrriox"

[[dependencies.recraftcollect]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.recraftcollect]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
